name             "load-balancer"
maintainer       "Enzo Haussecker"
maintainer_email "enzo@mirror.co"
license          "MIT"
version          "0.1.0"
recipe           "load-balancer::default", "This recipe configures a load balancer."
depends          "apt"
