name             "service-discovery"
maintainer       "Enzo Haussecker"
maintainer_email "enzo@mirror.co"
license          "MIT"
version          "0.1.0"
recipe           "service-discovery::default", "This recipe configures a single-node Consul cluster."
depends          "apt"
